### ISSUE TITLE
1.9 startup error (build 11)

### ISSUE THREAD

**Issue by leasoncre** [Morphan1/Builder#2]
Citizens version 2.0.17-SNAPSHOT (build 1326)
builder (build 11)
This server is running CraftBukkit version git-Spigot-b1c1b55-7d330bc (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

Will not load on startup, plugin not previously installed

```
[19:40:36] [Server thread/ERROR]: Could not load 'plugins\Builder b11.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/aufdemrand/denizencore/scripts/ScriptEntryData
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/denizencore/scripts/ScriptEntryData
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_74]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizencore.scripts.ScriptEntryData
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_74]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	... 6 more
```

**Comment by mcmonkey4eva** [comment]
Make sure you have latest Denizen - http://ci.citizensnpcs.co/job/Denizen/ - installed as well. Not sure why, but it's a dependency atm.

**Comment by leasoncre** [comment]
that fixed that error. (minor error? posting @denezins if it repeats on 2nd restart)

**Comment by Morphan1** [comment]
Whoops! Must have imported things I wasn't supposed to when updating the Denizen link at some point. This should be fixed in the [latest Builder build](http://ci.citizensnpcs.co/job/Builder/lastSuccessfulBuild/).

**Comment by leasoncre** [comment]
lol, plz try again. PS i assume the builder.jar can be renamed without causing error?
```
20:21:07] [Server thread/ERROR]: Could not load 'plugins\Builder b12.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/aufdemrand/denizencore/scripts/ScriptEntryData
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: net/aufdemrand/denizencore/scripts/ScriptEntryData
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_74]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizencore.scripts.ScriptEntryData
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_74]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_74]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.9.jar:git-Spigot-b1c1b55-7d330bc]
	... 6 more
```

**Comment by Morphan1** [comment]
Your error no longer makes sense

**Comment by leasoncre** [comment]
i removed denizens to retest this. was i not supposed to?
looks liek the souce, but idk what it is `java.lang.NoClassDefFoundError: net/aufdemrand/denizencore/scripts/ScriptEntryData`
